# Generated by Django 5.1.7 on 2025-06-12 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "create_timestamp",
                    models.DateTimeField(auto_created=True, auto_now=True, null=True),
                ),
                (
                    "event_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="event_id",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("venue", models.TextField()),
                ("total_participants", models.IntegerField(db_default=0, default=0)),
                ("title", models.CharField(default="An event", max_length=255)),
                ("description", models.TextField(db_default="")),
                (
                    "event_type",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_default="private",
                        default="Private",
                        max_length=15,
                        verbose_name="event_type",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
