# Generated by Django 5.1.7 on 2025-04-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "create_timestamp",
                    models.DateTimeField(auto_created=True, auto_now=True, null=True),
                ),
                (
                    "event_id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="event_id",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("venue", models.TextField()),
                ("total_participants", models.IntegerField(db_default=0, default=0)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "create_timestamp",
                    models.DateTimeField(auto_created=True, auto_now=True, null=True),
                ),
                (
                    "invite_id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="invite_id",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        verbose_name="status",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ems.event"
                    ),
                ),
                (
                    "invite_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="from",
                    ),
                ),
                (
                    "invite_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="to",
                    ),
                ),
            ],
        ),
    ]
