# Generated by Django 5.1.7 on 2025-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='req_type',
            field=models.CharField(blank=True, choices=[('invitation', 'Invitation'), ('participation', 'Participation')], default='invitation'),
        ),
    ]
