# Generated by Django 5.1.7 on 2025-04-27 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('create_timestamp', models.DateTimeField(auto_created=True, auto_now=True, null=True)),
                ('invite_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='invite_id')),
                ('receiver_email', models.EmailField(default='anonymususer@ems.com', max_length=254, verbose_name='receiver_email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_default='pending', default='Pending', verbose_name='status')),
                ('req_type', models.CharField(blank=True, choices=[('invitation', 'Invitation'), ('participation', 'Participation')], default='invitation')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='ems.event')),
                ('sent_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to=settings.AUTH_USER_MODEL, verbose_name='from')),
                ('sent_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to=settings.AUTH_USER_MODEL, verbose_name='to')),
            ],
        ),
    ]
