# Generated by Django 5.1.7 on 2025-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(db_default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='An event', max_length=255),
        ),
    ]
