# Generated by Django 5.1.7 on 2025-04-11 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_alter_invite_event_alter_invite_invite_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='invite_id'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_to', to=settings.AUTH_USER_MODEL, verbose_name='to'),
        ),
    ]
