# Generated by Django 5.1.7 on 2025-04-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0007_alter_invite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="receiver_email",
            field=models.EmailField(
                default="anonymususer@ems.com",
                max_length=254,
                verbose_name="receiver_email",
            ),
        ),
    ]
